import { Palette, Theme } from "../tokens.slint";
import { KVRow } from "../shells/kv-row.slint";
import { MicroButton } from "../primitives/button.slint";
import { CopyIcon } from "../icons/copy-icon.slint";

export component WalletAddressRow inherits Rectangle {
    in property <string> address;

    KVRow {
        label: @tr("Lightning address");
        sublabel: @tr("People can zap you via this address.");
        value: address;
        MicroButton {
            label: @tr("Copy");
            CopyIcon {
                stroke: Palette.text-mid;
            }
        }
    }
}
