import { Palette, Theme } from "../tokens.slint";

export component InfoRow inherits Rectangle {
    in property <string> label;
    in property <string> sublabel;
    in property <string> value;
    in property <bool> show-divider: true;

    height: 60px;
    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;
        padding-top: 12px;
        padding-bottom: 12px;
        spacing: 16px;
        alignment: stretch;
        VerticalLayout {
            horizontal-stretch: 1;
            spacing: 4px;
            alignment: center;
            Text {
                text: root.label;
                color: Palette.text-hi;
                font-size: (12px) * Theme.fs-scale;
                font-weight: 700;
            }

            Text {
                text: root.sublabel;
                color: Palette.text-lo;
                font-size: (11px) * Theme.fs-scale;
            }
        }

        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                alignment: end;
                spacing: 10px;
                Text {
                    text: root.value;
                    color: Palette.text-hi;
                    font-size: (12px) * Theme.fs-scale;
                    font-family: Theme.font;
                    vertical-alignment: center;
                }

                @children
            }
        }
    }

    if root.show-divider: Rectangle {
        y: parent.height - 1px;
        width: parent.width;
        height: 1px;
        background: Palette.border-2;
    }
}
