import { Palette } from "../tokens.slint";

export component CopyIcon inherits Rectangle {
    in property <color> stroke: Palette.text-mid;
    in property <color> fill: Palette.bg;
    width: 14px;
    height: 14px;
    Rectangle {
        x: 3px;
        y: 0;
        width: 10px;
        height: 11px;
        border-radius: 1.5px;
        border-width: 1.2px;
        border-color: root.stroke;
    }

    Rectangle {
        x: 0;
        y: 3px;
        width: 10px;
        height: 11px;
        border-radius: 1.5px;
        background: root.fill;
        border-width: 1.2px;
        border-color: root.stroke;
    }
}
